-- MySQL Script generated by MySQL Workbench
-- Wed Jul  4 18:34:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
START TRANSACTION;



-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `testdb`.`TieuDe`
-- -----------------------------------------------------
CREATE TABLE `TieuDe` (
  `maTieuDe` VARCHAR(10) NOT NULL,
  `tenTieuDe` VARCHAR(45) NULL,
  `loaiDia` VARCHAR(45) NULL,
  `moTa` VARCHAR(200) NULL,
  `thoiGianThue` INT NULL,
  `giaThue` DOUBLE NULL,
  PRIMARY KEY (`maTieuDe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`BangDia`
-- ----------------------------------------------------

COMMIT;

